const questions = [
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
];

export function getQuestions() {
  return questions;
}
