const questions = [
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is RAM?",
    a: "Random Access Memory",
    b: "Introduction and Communication",
    c: "All of the above",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ROM?",
    a: "Random Access Memory",
    b: "Read Only Memory",
    c: "All of the Above",
    d: "None of the above",
    answer: "b",
  },
  {
    question: "Who invented BASIC",
    a: "McLorry John",
    b: "John Kemeny & Thomas Kurtz",
    c: "Thomas Van",
    d: "None of the above",
    answer: "b",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
  {
    question: "What is ICT?",
    a: "Information and Communication Technology",
    b: "Introduction and Communication",
    c: "Intro and Comp. Technology",
    d: "None of the above",
    answer: "a",
  },
];

export function getQuestions() {
  return questions;
}
